version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_DB_URI: mongodb://mongo:27017/monsters 
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
    - app_network
networks:
  app_network:
    driver: bridge
